In [1]:
import torch

torch.__version__

'2.5.1+cu118'

### 기본적인 텐서 생성

In [3]:
x = torch.empty(4,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
x = torch.rand(4,2)
x

tensor([[0.1495, 0.1493],
        [0.1233, 0.9083],
        [0.7587, 0.5495],
        [0.5167, 0.4902]])

In [8]:
x = torch.zeros(4,2,dtype=torch.long)
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [10]:
x = torch.tensor([3, 2.3])
x

tensor([3.0000, 2.3000])

In [12]:
x = x.new_ones(2, 4, dtype=torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [14]:
x = torch.randn_like(x, dtype=torch.double)
x

tensor([[ 0.4128, -0.3470,  0.0600,  1.8772],
        [-0.7766,  1.0804,  0.4788, -0.8328]], dtype=torch.float64)

In [15]:
print(x.size())

torch.Size([2, 4])


In [17]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


### CUDA Tensors
* .to 메소드로 텐서를 cpu, gpu로 옮길 수 있다.

In [18]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-1.2350])
-1.2349838018417358
torch.float32


In [21]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

y = torch.ones_like(x, device=device)
print(y)

x = x.to(device)
print(x)

z = x+y
print(z)

print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([-1.2350], device='cuda:0')
tensor([-0.2350], device='cuda:0')
tensor([-0.2350], dtype=torch.float64)


### 연산

In [26]:
import math

a = torch.rand(1,2)*2-1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.1, 0.1))

tensor([[-0.2642, -0.6098]])
tensor([[0.2642, 0.6098]])
tensor([[-0., -0.]])
tensor([[-1., -1.]])
tensor([[-0.1000, -0.1000]])


In [27]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.1871, 0.6086],
        [0.2550, 0.2466]])
torch.return_types.max(
values=tensor([0.2550, 0.6086]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([0.6086, 0.2550]),
indices=tensor([1, 0]))


### 인덱싱

In [28]:
x = torch.Tensor([[1,2], [3,4]])

print(x)

print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

print(x[:,0])
print(x[:,1])

print(x[0,:])
print(x[1,:])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


### 크기나 모양 변경

In [30]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = x.view(5,-1)
print(z)
m = x.view(-1, 2)
print(m)

tensor([[-0.2849,  0.6462, -0.9774, -0.1782, -0.8323],
        [-1.0276, -0.9507, -1.2554, -0.3670,  0.2826],
        [ 0.3949, -0.9014,  2.0186,  0.6001,  0.5610],
        [-0.1516, -0.6914,  1.4947,  0.3096,  1.9638]])
tensor([-0.2849,  0.6462, -0.9774, -0.1782, -0.8323, -1.0276, -0.9507, -1.2554,
        -0.3670,  0.2826,  0.3949, -0.9014,  2.0186,  0.6001,  0.5610, -0.1516,
        -0.6914,  1.4947,  0.3096,  1.9638])
tensor([[-0.2849,  0.6462, -0.9774, -0.1782],
        [-0.8323, -1.0276, -0.9507, -1.2554],
        [-0.3670,  0.2826,  0.3949, -0.9014],
        [ 2.0186,  0.6001,  0.5610, -0.1516],
        [-0.6914,  1.4947,  0.3096,  1.9638]])
tensor([[-0.2849,  0.6462],
        [-0.9774, -0.1782],
        [-0.8323, -1.0276],
        [-0.9507, -1.2554],
        [-0.3670,  0.2826],
        [ 0.3949, -0.9014],
        [ 2.0186,  0.6001],
        [ 0.5610, -0.1516],
        [-0.6914,  1.4947],
        [ 0.3096,  1.9638]])
