In [1]:
import torch

torch.__version__

'2.5.1+cu124'

### 기본적인 텐서 생성

In [2]:
x = torch.empty(4,2)
x

tensor([[-1.1289e-36,  1.0243e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [3]:
x = torch.rand(4,2)
x

tensor([[0.3831, 0.7022],
        [0.7381, 0.0017],
        [0.2649, 0.6227],
        [0.3138, 0.8010]])

In [4]:
x = torch.zeros(4,2,dtype=torch.long)
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [5]:
x = torch.tensor([3, 2.3])
x

tensor([3.0000, 2.3000])

In [6]:
x = x.new_ones(2, 4, dtype=torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [7]:
x = torch.randn_like(x, dtype=torch.double)
x

tensor([[-1.2240, -0.2892,  1.4559, -2.1971],
        [ 1.0893,  0.8927,  0.1365, -0.3622]], dtype=torch.float64)

In [8]:
print(x.size())

torch.Size([2, 4])


In [9]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


### CUDA Tensors
* .to 메소드로 텐서를 cpu, gpu로 옮길 수 있다.

In [10]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.6229])
0.6228950619697571
torch.float32


In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

y = torch.ones_like(x, device=device)
print(y)

x = x.to(device)
print(x)

z = x+y
print(z)

print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([0.6229], device='cuda:0')
tensor([1.6229], device='cuda:0')
tensor([1.6229], dtype=torch.float64)


### 연산

In [12]:
import math

a = torch.rand(1,2)*2-1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.1, 0.1))

tensor([[ 0.4450, -0.3918]])
tensor([[0.4450, 0.3918]])
tensor([[1., -0.]])
tensor([[ 0., -1.]])
tensor([[ 0.1000, -0.1000]])


In [13]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.9094, 0.8896],
        [0.0798, 0.7641]])
torch.return_types.max(
values=tensor([0.9094, 0.8896]),
indices=tensor([0, 0]))
torch.return_types.max(
values=tensor([0.9094, 0.7641]),
indices=tensor([0, 1]))


### 인덱싱

In [14]:
x = torch.Tensor([[1,2], [3,4]])

print(x)

print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

print(x[:,0])
print(x[:,1])

print(x[0,:])
print(x[1,:])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


### 크기나 모양 변경

In [15]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = x.view(5,-1)
print(z)
m = x.view(-1, 2)
print(m)

tensor([[-0.4053,  1.1408, -1.2392,  2.0316,  0.8105],
        [ 0.5459,  1.8204, -0.7542,  1.2955, -0.0757],
        [-0.0413,  0.5955, -0.8474, -1.4523,  2.3011],
        [-0.5990, -0.5245,  1.7594, -0.8098, -0.4066]])
tensor([-0.4053,  1.1408, -1.2392,  2.0316,  0.8105,  0.5459,  1.8204, -0.7542,
         1.2955, -0.0757, -0.0413,  0.5955, -0.8474, -1.4523,  2.3011, -0.5990,
        -0.5245,  1.7594, -0.8098, -0.4066])
tensor([[-0.4053,  1.1408, -1.2392,  2.0316],
        [ 0.8105,  0.5459,  1.8204, -0.7542],
        [ 1.2955, -0.0757, -0.0413,  0.5955],
        [-0.8474, -1.4523,  2.3011, -0.5990],
        [-0.5245,  1.7594, -0.8098, -0.4066]])
tensor([[-0.4053,  1.1408],
        [-1.2392,  2.0316],
        [ 0.8105,  0.5459],
        [ 1.8204, -0.7542],
        [ 1.2955, -0.0757],
        [-0.0413,  0.5955],
        [-0.8474, -1.4523],
        [ 2.3011, -0.5990],
        [-0.5245,  1.7594],
        [-0.8098, -0.4066]])


### item
스칼라가 하나만 있어야 가능

In [16]:
x = torch.randn(1)
print(x.item())
print(x.dtype)

-2.2040650844573975
torch.float32


### squeeze

In [17]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.1352, 0.0085, 0.2651],
         [0.0782, 0.2405, 0.2358],
         [0.2804, 0.3154, 0.4986]]])
torch.Size([1, 3, 3])


In [18]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.1352, 0.0085, 0.2651],
        [0.0782, 0.2405, 0.2358],
        [0.2804, 0.3154, 0.4986]])
torch.Size([3, 3])


In [19]:
t.unsqueeze(dim=0) # 1,3,3

tensor([[[0.1352, 0.0085, 0.2651],
         [0.0782, 0.2405, 0.2358],
         [0.2804, 0.3154, 0.4986]]])

In [20]:
t.unsqueeze(dim=1) # 3,1,3

tensor([[[0.1352, 0.0085, 0.2651]],

        [[0.0782, 0.2405, 0.2358]],

        [[0.2804, 0.3154, 0.4986]]])

### stack

In [21]:
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2,5])
print(y)
z = torch.FloatTensor([3,6])
print(z)

print(torch.stack([x,y,z]))


tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### concat

In [22]:
a = torch.randn(1,3,3)
print(a)
b = torch.randn(1,3,3)
print(b)
c = torch.cat((a,b), dim=0)
print(c)
print(c.size())

tensor([[[ 1.2180, -0.8358, -0.6941],
         [ 0.2835, -1.8649, -0.8072],
         [ 1.3806, -0.5297, -0.1719]]])
tensor([[[-1.8086,  0.2357,  0.1399],
         [ 0.2157, -0.0529,  0.1281],
         [ 1.5482, -1.1254, -1.1607]]])
tensor([[[ 1.2180, -0.8358, -0.6941],
         [ 0.2835, -1.8649, -0.8072],
         [ 1.3806, -0.5297, -0.1719]],

        [[-1.8086,  0.2357,  0.1399],
         [ 0.2157, -0.0529,  0.1281],
         [ 1.5482, -1.1254, -1.1607]]])
torch.Size([2, 3, 3])


In [23]:
c = torch.cat((a,b), dim=1)
print(c)
print(c.size())

tensor([[[ 1.2180, -0.8358, -0.6941],
         [ 0.2835, -1.8649, -0.8072],
         [ 1.3806, -0.5297, -0.1719],
         [-1.8086,  0.2357,  0.1399],
         [ 0.2157, -0.0529,  0.1281],
         [ 1.5482, -1.1254, -1.1607]]])
torch.Size([1, 6, 3])


In [24]:
c = torch.cat((a,b), dim=2)
print(c)
print(c.size())

tensor([[[ 1.2180, -0.8358, -0.6941, -1.8086,  0.2357,  0.1399],
         [ 0.2835, -1.8649, -0.8072,  0.2157, -0.0529,  0.1281],
         [ 1.3806, -0.5297, -0.1719,  1.5482, -1.1254, -1.1607]]])
torch.Size([1, 3, 6])


### chunk

In [25]:
tensor = torch.rand(3,6)
print(tensor)

t1, t2, t3 = torch.chunk(tensor, 3, dim=1)

tensor([[0.8262, 0.7280, 0.5111, 0.3008, 0.6205, 0.4830],
        [0.0637, 0.0255, 0.1915, 0.6094, 0.1251, 0.6518],
        [0.8132, 0.7773, 0.7062, 0.4638, 0.0351, 0.9031]])


In [26]:
print(t1)
print(t2)
print(t3)

tensor([[0.8262, 0.7280],
        [0.0637, 0.0255],
        [0.8132, 0.7773]])
tensor([[0.5111, 0.3008],
        [0.1915, 0.6094],
        [0.7062, 0.4638]])
tensor([[0.6205, 0.4830],
        [0.1251, 0.6518],
        [0.0351, 0.9031]])


In [27]:
t1, t2, t3 = torch.chunk(tensor, 3, dim=0)

print(t1)
print(t2)
print(t3)

tensor([[0.8262, 0.7280, 0.5111, 0.3008, 0.6205, 0.4830]])
tensor([[0.0637, 0.0255, 0.1915, 0.6094, 0.1251, 0.6518]])
tensor([[0.8132, 0.7773, 0.7062, 0.4638, 0.0351, 0.9031]])


### split
chunk와 달리 어떤 크기의 텐서로 나눌 것인지를 입력

In [28]:
tensor = torch.rand(3,6)
t1, t2 = torch.split(tensor, 3, dim=1)

In [29]:
print(t1)
print(t2)

tensor([[0.3759, 0.1123, 0.1188],
        [0.8110, 0.5877, 0.7239],
        [0.5224, 0.8058, 0.7932]])
tensor([[0.2966, 0.0704, 0.9647],
        [0.5114, 0.5513, 0.9471],
        [0.0285, 0.5061, 0.7753]])


### torch와 numpy의 상호변환

In [30]:
a = torch.ones(6)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1.]


In [31]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2.]


텐서가 cpu상에 있으면 메모리를 공유하므로 같이 변함

In [32]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


### Autograd(자동미분)

* torch.autograd: Tensor의 모든 연산에 대해 자동 미분 제공
* 역전파(backprop)에 사용

In [33]:
a = torch.randn(3,3)
a*=3
print(a)
print(a.requires_grad)

tensor([[ 2.0203,  1.5061,  6.8237],
        [-2.4898, -2.2844,  1.4609],
        [-2.8778, -2.7915,  9.2767]])
False


In [34]:
a.requires_grad_(True)
print(a.requires_grad)

b = (a*a).sum()
print(b)
print(b.grad_fn)

True
tensor(168.5964, grad_fn=<SumBackward0>)


### 그래디언트 구하기

In [35]:
x = torch.ones(3, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [36]:
y = x+5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [37]:
z = y*y
out = z.mean()
print(z, out)

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)


In [38]:
print(out)
out.backward()

tensor(36., grad_fn=<MeanBackward0>)


In [39]:
print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [40]:
x = torch.randn(3, requires_grad=True)

y = x*2
while y.data.norm() < 1000:
    y = y*2

print(y)

tensor([ -125.0663, -1321.9078,  1282.9073], grad_fn=<MulBackward0>)


In [41]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


### with torch.no_grad()
* 기울기 계산을 하지 않지만 매개변수를 갖는 모델을 평가할 때 유용

In [ ]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print(x.requires_grad)
    print((x**2).requires_grad)

True
True
True
False


### detach
내용물은 같으나, require_grad가 다른 새로운 Tensor를 가져올 때

In [ ]:
print(x.requires_grad) # T
y = x.detach()
print(y.requires_grad) # F
print(x.eq(y).all())

True
False
tensor(True)


### Backpropagation

In [47]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [56]:
a = torch.ones(2,2,requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [57]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
None
None


In [58]:
b = a + 2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [61]:
c = b ** 2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [62]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [63]:
out.backward()

In [70]:
print(a.grad)

tensor([[6., 6.],
        [6., 6.]])


In [71]:
print(c.grad)
print(c.grad_fn)
print(c.data)
print('\n')
print(b.grad)
print(b.grad_fn)
print(b.data)
print('\n')
print(a.grad)
print(a.grad_fn)
print(a.data)

None
tensor([[9., 9.],
        [9., 9.]])


None
tensor([[3., 3.],
        [3., 3.]])


tensor([[6., 6.],
        [6., 6.]])
None
tensor([[1., 1.],
        [1., 1.]])


C:\Users\jongcheol\AppData\Local\Temp\ipykernel_15652\1042403374.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print(c.grad)
C:\Users\jongcheol\AppData\Local\Temp\ipykernel_15652\1042403374.py:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If y

In [55]:
print(out.grad)
print(out.grad_fn)
print(out.data)

None
tensor(36.)


C:\Users\jongcheol\AppData\Local\Temp\ipykernel_15652\1499947373.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print(out.grad)
