In [2]:
import tensorflow as tf

In [3]:
a=tf.constant([[1,2,3],
                [4,5,6]])
print(a);print(a.shape);print(a.dtype)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
<dtype: 'int32'>


tr.constant()로 텐서 생성

In [4]:
a[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [5]:
a1 = a[...,1]
a1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [6]:
a2 = a[...,1,tf.newaxis]
a2

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [7]:
b0 = a+100
b0

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[101, 102, 103],
       [104, 105, 106]])>

In [8]:
b1 = tf.square(a)
b1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [9]:
a.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
import numpy as np
c = np.array([[1,2],
              [3,4],
              [5,6]])

d1 = tf.transpose(c)
d2 = c.T

print(c);print(d1);print(d2)

[[1 2]
 [3 4]
 [5 6]]
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
[[1 3 5]
 [2 4 6]]


In [16]:
print(type(d1))
print(type(d2))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'numpy.ndarray'>


In [ ]:
A=tf.constant([[1,2,3],[4,5,6]])
tf.transpose(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

* A.T 하면 오류 발생
* tensor는 자료의 type이 일치되어야 연산 가능

In [19]:
t1=tf.constant(1)
t2=tf.constant(2.)

In [21]:
tf.cast(t1,tf.float32)+t2

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

* **tf.constant()**로 생성한 자료는 slicing, 연산 등은 가능하나 자료를 수정할 수 없다. (튜플 비슷한 느낌)
* tf.Variable()을 이용하면 수정 가능한 텐서를 생성가능

In [22]:
k=tf.Variable([[1.,2,3],[4,5,6]])
print(k)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
