In [2]:
!pip install tensorflow

     -------------------------------------- 390.2/390.2 MB 3.6 MB/s eta 0:00:00
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ---------------------------------------- 71.9/71.9 kB 1.3 MB/s eta 0:00:00
     -------------------------------------- 431.5/431.5 kB 3.0 MB/s eta 0:00:00
     ---------------------------------------- 4.4/4.4 MB 3.0 MB/s eta 0:00:00
     ---------------------------------------- 5.5/5.5 MB 3.6 MB/s eta 0:00:00
     ---------------------------------------- 1.2/1.2 MB 4.4 MB/s eta 0:00:00
     ---------------------------------------- 3.0/3.0 MB 4.6 MB/s eta 0:00:00
     -------------------------------------- 126.7/126.7 kB 1.5 MB/s eta 0:00:00
  Using cached tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl (1.5 MB)
     -------------------------------------- 242.4/242.4 kB 2.1 MB/s eta 0:00:00
     ----------------------


[notice] A new release of pip available: 22.3.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import tensorflow as tf

In [4]:
a=tf.constant([[1,2,3],
                [4,5,6]])
print(a);print(a.shape);print(a.dtype)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
<dtype: 'int32'>


tr.constant()로 텐서 생성

In [10]:
a[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [12]:
a1 = a[...,1]
a1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [13]:
a2 = a[...,1,tf.newaxis]
a2

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [15]:
b0 = a+100
b0

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[101, 102, 103],
       [104, 105, 106]])>

dddddddddlldll

In [ ]:
b1 = tf.square(a)
b1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [17]:
a.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
import numpy as np
c = np.array([[1,2],
              [3,4],
              [5,6]])

d1 = tf.transpose(c)
d2 = c.T

print(c);print(d1);print(d2)

[[1 2]
 [3 4]
 [5 6]]
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
[[1 3 5]
 [2 4 6]]
